version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: logistics_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: logistics
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: logistics_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8050:8050"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: logistics
      DB_USER: root
      DB_PASSWORD: rootpassword123
    volumes:
      - .:/app
    

volumes:
  db_data:
